import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from "next/font/google"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

//Custom Fonts
const Outfitfont  = Outfit({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap"
}) 

export const metadata = {
  title: "E-Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Outfitfont.className} antialiased`}
      >
        {children}
      </body>
    </html>

  );
}
